name: Add comment if pr merges into master

on:
  pull_request
  
permissions:
  pull-requests: write

jobs:
  AddComment:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master' }}
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.pulls.createReviewComment({
            pull_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_id: context.sha,
            path: '',
            body: 'ðŸ‘‹ This pr is going into master!'
          })
