name: Add comment if pr merges into master

on:
  pull_request

jobs:
  LogGithub:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  AddComment:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'refs/heads/master' }}
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.pulls.createReviewComment({
            pull_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_id: context.sha,
            path: '',
            body: 'ðŸ‘‹ This pr is going into master!'
          })
